/**
 * @file tpl_cortex_definitions.h
 *
 * @section descr File description
 *
 * Defines related to the cortex target platform
 *
 * Generated from application casioCAN_plus
 * Automatically generated by goil on Www Mmm dd hh:mm:ss yyyy
 * from root OIL file CasioCANplus.oil
 *
 * @section infos File informations
 *
 * $$Date$$
 * $$Rev$$
 * $$Author$$
 * $$URL$$
 */

#ifndef TPL_CORTEX_DEFINITIONS_H
#define TPL_CORTEX_DEFINITIONS_H
  
/*-----------------------------------------------------------------------------
 * File generated for target cortex-m/armv6m/stm32g0b1
 * Number of priority bits :      2
 */
#define PRIO_BITS_IN_NVIC             2

/*
 * Priorities are unshifted and intended to be used in NVIC_SetPriority
 */
#define KERNEL_PRIO_UNSHIFTED         0
#define OS_ISR_PRIO_UNSHIFTED         3
#define ISR1_IT_PRIO_UNSHIFTED        1

/*
 * Priorities are shifted and intended to be stored in BASEPRI
 */
#define KERNEL_PRIO         0          /* Unshifted priority: 0 */
#define OS_ISR_PRIO       192          /* Unshifted priority: 3 */
#define ISR1_IT_PRIO       64          /* Unshifted priority: 1 */

/*
 * Interrupt numbers for interrupt sources used by ISR
 */
#define TIM16_FDCAN_IT0_IRQ_Number             21

/*
 * Computed priorities for interrupt sources used by ISR category 1
 * Priorities are unshifted and intended to be used in NVIC_SetPriority
 */
#define TIM16_FDCAN_IT0_IRQ_Priority            2

/* TPL_CORTEX_DEFINITIONS_H */
#endif

/* End of file tpl_cortex_definitions.h */
