/**
 * @file tpl_external_interrupts.c
 *
 * @section desc File description
 *
 * External interrupts init and acknowledge functions for readbutton_isr
 * Automatically generated by goil on Www Mmm dd hh:mm:ss yyyy
 * from root OIL file readbutton_isr.oil
 *
 * @section copyright Copyright
 *
 * Trampoline OS
 *
 * Trampoline is copyright (c) IRCCyN 2005-2007
 * Trampoline is protected by the French intellectual property law.
 *
 * This software is distributed under the GNU Public Licence v2
 *
 */

#include "tpl_machine.h"
#include "tpl_cortex_definitions.h"
#include "pinAccess.h"


/*
 * External Interrupts initialization for the STM32G0B1 Microcontroller
 *
 * Interrupt vectors are EXTI0_IRQ, EXTI1_IRQ, EXTI2_IRQ, EXTI3_IRQ, EXTI4_IRQ
 * EXTI5_9_IRQ and EXTI15_10_IRQ
 *
 * Inits are done according to the source(s) pin(s) selected for an interrupt
 * vector corresponding to an or a set of interrupt(s) line(s)
 */
#define OS_START_SEC_CODE
#include "tpl_memmap.h"

FUNC(void, OS_CODE) tpl_init_external_interrupts()
{
// ---

    /* Program the pins of the GPIO */
    pinMode(GPIOA,3,INPUT_PULLUP);

    /* Set the clock for SYSCFG */  
    RCC->APBENR2 |= RCC_APBENR2_SYSCFGEN;
    RCC->APBENR2; /* force read access */

    /* Set Interrupt Mask Register */
    EXTI->IMR1 |= EXTI_IMR1_IM3;

    /* select port associated to each interrupt */
    SYSCFG->IT_LINE_SR[6] &= ~SYSCFG_ITLINE6_SR_EXTI3; /*PA3*/
    SYSCFG->IT_LINE_SR[6] |=  SYSCFG_ITLINE6_SR_EXTI3; /* isr on PA3 */

    /* select trigger mode - RISING, FALLIN, BOTH */
    EXTI->RTSR1 &= ~EXTI_RTSR1_RT3; /* PA3 : FALLING */
    EXTI->FTSR1 |=  EXTI_FTSR1_FT3;

// -------------------------------------------------------------------------------------

  /* Program the NVIC */

    NVIC_SetPriority(EXTI2_3_IRQn,OS_ISR_PRIO_UNSHIFTED);
    NVIC_EnableIRQ(EXTI2_3_IRQn);

}

#define OS_STOP_SEC_CODE
#include "tpl_memmap.h"

/* End of file tpl_external_interrupts.c */

